name: Snapshot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
          key: ${{ runner.os }}-${{ hashFiles('**/*.sbt') }}
      - name: Build
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayKey: ${{ secrets.bintrayKey }}
        run: |
          git fetch --unshallow --tags
          cat /dev/null | project/sbt storeBintrayCredentials
          cat /dev/null | project/sbt clean test publish
